services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: cleannode-api
    image: node:20.10.0
    working_dir: /app
    command: bash -c "npm run dev"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ADDRESS=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../../:/app
    ports:
      - '${APPLICATION_PORT}:5050'
    depends_on:
      - db
